# Cómo buscar cada ingrediente de la app en los supermercados.
# q: palabras que tienen que aparecer todas en el nombre del producto
# c: secciones de Mercadona donde buscar (evita papillas, comida de mascotas…)
# x: palabras que descartan el producto
# b: texto de búsqueda en Dia y Consum (si no, se usa q)
# u: gramos por unidad cuando el producto se vende por unidades (huevos…)
# de: se calcula a partir de otro ingrediente (cocido a partir de crudo), con el rendimiento r (g cocinado por g crudo)
FRUTA = ['Cítricos', 'Fruta tropical', 'Manzana y pera', 'Otras frutas', 'Plátano y uva', 'Melón y sandía']
VERD = ['Calabacín y pimiento', 'Cebolla y ajo', 'Hierbas aromáticas', 'Otras verduras y hortalizas', 'Patata', 'Pepino y zanahoria', 'Repollo y col', 'Setas y champiñones', 'Tomate', 'Lechuga', 'Ensalada preparada']
SEM = ' salsa zumo mermelada papilla bolsita tarrito puree pure batido yogur galleta barrita helado chips snack deshidratad desecad confitad'
M = {
 'Aceite de oliva': dict(q='aceite oliva', c=['Aceite de oliva'], x='spray orujo', b='aceite de oliva'),
 'Aguacate': dict(q='aguacate', c=FRUTA, x=SEM + ' guacamole'),
 'Ajo': dict(q='ajo', c=['Cebolla y ajo'], x='picada perejil negro pelado triturado', b='ajos'),
 'Almendras': dict(q='almendra', c=['Frutos secos'], x='chocolate miel garrapi', b='almendra natural'),
 'Alubias cocidas': dict(q='alubia', c=['Alubias'], x='fabada estofad chorizo'),
 'Arroz blanco crudo': dict(q='arroz', c=['Arroz'], x='integral basmati cocido vaso thai jazmin bomba salvaje sabroz risotto quinoa', b='arroz redondo'),
 'Arroz blanco cocido': dict(de='Arroz blanco crudo', r=2.6),
 'Arroz integral crudo': dict(q='arroz integral', c=['Arroz'], x='cocido vaso sabroz tortita'),
 'Arroz integral cocido': dict(de='Arroz integral crudo', r=2.5),
 'Atún al natural (escurrido)': dict(q='atun natural', c=['Atún'], x='pack aceite'),
 'Avena en copos': dict(q='copos avena', c=['Cereales', 'Cereales integrales y muesli'], x='chocolate muesli', b='copos de avena'),
 'Azúcar': dict(q='azucar', c=['Azúcar'], x='moreno panela glas caña sobres', b='azucar blanco'),
 'Bacalao desalado': dict(q='bacalao', c=['Pescado', 'Pescado congelado', 'Salazones', 'Bacalao'], x='piquillo migas dorado rebozad', b='bacalao desalado'),
 'Bebida de almendras sin azúcar': dict(q='bebida almendra', c=['Bebidas vegetales'], x='chocolate', b='bebida almendras sin azucar'),
 'Berenjena': dict(q='berenjena', c=VERD, x='rellen'),
 'Boniato crudo': dict(q='', o='boniato batata', c=VERD + ['Patatas'], x='frito asado bastones microondas', b='boniato'),
 'Brócoli': dict(q='brocoli', c=VERD + ['Verduras al vapor'], x='coliflor rehogad', b='brocoli'),
 'Bulgur crudo': dict(q='bulgur', c=None, x='ensalada'),
 'Burrata': dict(q='burrata', c=['Queso fresco', 'Queso especialidades'], x='pizza'),
 'Cacahuetes': dict(q='cacahuete', c=['Frutos secos', 'Cocktails'], x='miel crema chocolate frito cocktail mezcla', b='cacahuete tostado'),
 'Cacao puro en polvo': dict(q='cacao puro', c=['Cacao soluble', 'Chocolate a la taza', 'Levadura y preparado repostería'], x='soluble instant', b='cacao puro'),
 'Café solo': dict(q='cafe molido', c=['Café molido'], x='descafeinado', b='cafe molido natural', r=12.5),
 'Calabacín': dict(q='calabacin', c=VERD, x='espiral tallarin crema', b='calabacin'),
 'Calabaza': dict(q='calabaza', c=VERD, x='crema pipas', b='calabaza'),
 'Caldo de pollo': dict(q='caldo pollo', c=['Caldo líquido'], x='casero', b='caldo de pollo'),
 'Caldo de verduras': dict(q='caldo verdura', c=['Caldo líquido'], x='', b='caldo de verduras'),
 'Canela molida': dict(q='canela molida', c=['Otras especias'], x='', b='canela molida'),
 'Carne picada de pavo': dict(q='picada pollo', c=['Picadas y otros', 'Pavo y otras aves', 'Pollo'], x='', b='carne picada pollo'),
 'Carne picada de vacuno': dict(q='picada vacuno', c=['Picadas y otros', 'Vacuno'], x='cerdo', b='carne picada vacuno'),
 'Cebolla': dict(q='cebolla', c=['Cebolla y ajo'], x='frita tierna morada roja cebolleta caramelizada', b='cebolla'),
 'Cerdo, lomo crudo': dict(q='lomo cerdo', c=['Cerdo'], x='adobado iberico marinado ajillo', b='lomo de cerdo'),
 'Cerveza': dict(q='cerveza', c=['Cerveza botella y botellín', 'Cerveza lata'], x='sin alcohol 0,0 tostada radler', b='cerveza lata'),
 'Champiñones': dict(q='champi', c=['Setas y champiñones'], x='portobello laminado', b='champiñon'),
 'Chocolate negro 70%': dict(q='chocolate 70', c=['Chocolate negro'], x='', b='chocolate negro 70'),
 'Clara de huevo': dict(q='claras huevo', c=['Huevos'], x='', b='claras de huevo'),
 'Coliflor': dict(q='coliflor', c=VERD + ['Verduras al vapor'], x='brocoli arroz', b='coliflor'),
 'Copos de maíz sin azúcar': dict(q='corn flakes', c=['Cereales', 'Cereales integrales y muesli'], x='chocolate miel', b='corn flakes'),
 'Crema de cacahuete': dict(q='crema cacahuete', c=['Cremas de untar', 'Frutos secos', 'Otras salsas'], x='chocolate cacao', b='crema de cacahuete'),
 'Cuscús crudo': dict(q='', o='cuscus cous', c=['Arroz'], x='preparado ensalada', b='cous cous'),
 'Dátiles': dict(q='datil', c=['Fruta desecada', 'Otras frutas', 'Frutos secos'], x='bacon', b='datiles'),
 'Edamame': dict(q='edamame', c=None, x='', b='edamame'),
 'Especias variadas': dict(q='pimenton', c=['Colorante y pimentón'], x='picante', b='pimenton dulce'),
 'Espinacas': dict(q='espinaca', c=VERD + ['Verdura', 'Verduras al vapor'], x='crema tortilla nata', b='espinacas'),
 'Fideos de arroz (crudos)': dict(q='fideos arroz', c=['Fideos orientales', 'Fideos'], x='', b='fideos de arroz'),
 'Fresas': dict(q='fresa', c=FRUTA + ['Fruta'], x=SEM, b='fresas'),
 'Frutos rojos congelados': dict(q='frutos rojos', c=['Fruta', 'Otras frutas'], x=SEM, b='frutos rojos congelados'),
 'Galletas integrales': dict(q='galletas integral', c=['Galletas integrales y digestive'], x='chocolate', b='galletas integrales'),
 'Gambas peladas': dict(q='gamba pelada', c=['Marisco'], x='ajillo rebozad', b='gamba pelada congelada'),
 'Garbanzos cocidos': dict(q='garbanzo cocido', c=['Garbanzos'], x='espinaca', b='garbanzos cocidos'),
 'Guisantes': dict(q='guisante', c=['Verdura', 'Conservas verdura'], x='jamon', b='guisantes congelados'),
 'Harina de avena': dict(q='harina avena', c=None, x='', b='harina de avena'),
 'Harina de trigo': dict(q='harina trigo', c=['Harina'], x='integral fuerza reposteria espelta', b='harina de trigo'),
 'Hierbas frescas': dict(q='perejil', c=['Hierbas aromáticas', 'Hierbas'], x='ajo', b='perejil'),
 'Huevo entero': dict(q='huevos', c=['Huevos'], x='sorpresa codorniz', b='huevos', u=60),
 'Hummus': dict(q='hummus', c=['Hummus y otros'], x='piquillo aguacate remolacha', b='hummus'),
 'Jamón serrano': dict(q='jamon serrano', c=['Jamón serrano'], x='iberico taquitos', b='jamon serrano lonchas'),
 'Jengibre fresco': dict(q='jengibre', c=VERD, x='', b='jengibre'),
 'Judías verdes': dict(q='judia', c=VERD + ['Verdura', 'Conservas verdura'], x='', b='judias verdes'),
 'Kiwi': dict(q='kiwi', c=FRUTA, x=SEM, b='kiwi'),
 'Leche de coco light': dict(q='coco', c=['Otras salsas', 'Salsas orientales', 'Bebidas vegetales', 'Leche condensada y otros'], x='rallado arroz bebida', o='preparado leche', b='leche de coco'),
 'Leche desnatada': dict(q='leche desnatada', c=['Leche desnatada'], x='lactosa calcio', b='leche desnatada'),
 'Leche entera': dict(q='leche entera', c=['Leche entera'], x='lactosa', b='leche entera'),
 'Leche semidesnatada': dict(q='leche semidesnatada', c=['Leche semidesnatada'], x='lactosa calcio', b='leche semidesnatada'),
 'Lechuga': dict(q='lechuga', c=['Lechuga'], x='', b='lechuga', u=300),
 'Lentejas cocidas': dict(q='lenteja cocida', c=['Lentejas y otros'], x='', b='lentejas cocidas'),
 'Lentejas rojas crudas': dict(q='lenteja roja', c=['Lentejas y otros'], x='cocida', b='lentejas rojas'),
 'Levadura química': dict(q='', o='gasificante quimica', c=['Levadura y preparado repostería'], x='fresca panaderia', b='levadura quimica'),
 'Maicena': dict(q='harina maiz', c=['Harina'], x='precocida', b='maicena'),
 'Maíz dulce (lata)': dict(q='maiz dulce', c=['Conservas verdura'], x='', b='maiz dulce'),
 'Maíz para palomitas': dict(q='palomitas', c=['Snacks', 'Frutos secos', 'Legumbres', 'Lentejas y otros'], x='microondas caramelo dulce', b='maiz palomitas'),
 'Mango': dict(q='mango', c=FRUTA, x=SEM, b='mango', u=350),
 'Mantequilla': dict(q='mantequilla', c=['Mantequilla'], x='sal ajo', b='mantequilla'),
 'Manzana': dict(q='manzana', c=['Manzana y pera'], x=SEM, b='manzana golden'),
 'Mayonesa': dict(q='mayonesa', c=['Mayonesa'], x='light', b='mayonesa'),
 'Merluza cruda': dict(q='merluza', c=['Pescado', 'Pescado congelado', 'Merluza'], x='rebozad empanad papilla palitos romana pescadilla croqueta', b='merluza'),
 'Miel': dict(q='miel', c=['Miel'], x='', b='miel'),
 'Mostaza': dict(q='mostaza', c=['Mostaza'], x='miel', b='mostaza'),
 'Naranja': dict(q='naranja', c=['Cítricos'], x=SEM + ' refresco', b='naranja'),
 'Nueces': dict(q='nuez', c=['Frutos secos'], x='macadamia pecana miel', b='nueces'),
 'Ñoquis de patata': dict(q='gnocchi', c=['Pasta rellena', 'Pasta'], x='', b='gnocchi'),
 'Pan blanco': dict(q='pan', c=['Barra de pan', 'Pan de bocadillo'], x='integral centeno espelta semillas cereales', b='barra de pan'),
 'Pan integral': dict(q='pan integral', c=['Pan de molde', 'Barra de pan'], x='panela', b='pan integral'),
 'Pan pita integral': dict(q='pita', c=['Pan de hamburguesa y wrap', 'Otros panes'], x='', b='pan de pita'),
 'Papel de arroz': dict(q='arroz', c=['Fideos orientales', 'Otros panes'], x='fideos', b='papel de arroz', h='obleas'),
 'Pasta cruda': dict(q='macarron', c=['Macarrones, pajaritas y hélices'], x='integral lenteja garbanzo', b='macarrones'),
 'Pasta cocida': dict(de='Pasta cruda', r=2.3),
 'Pasta integral cruda': dict(q='integral', c=['Macarrones, pajaritas y hélices', 'Spaghetti y tallarines'], x='', b='macarrones integrales'),
 'Pasta integral cocida': dict(de='Pasta integral cruda', r=2.3),
 'Patata cruda': dict(q='patata', c=['Patata', 'Patatas'], x='frita dados gajos cocida', b='patatas'),
 'Pavo, pechuga cruda': dict(q='pechuga pavo', c=['Pavo y otras aves'], x='', b='pechuga de pavo filetes'),
 'Pechuga de pavo en lonchas': dict(q='pechuga pavo', c=['Pavo y otros'], x='', b='pechuga de pavo lonchas'),
 'Pechuga de pollo cruda': dict(q='pechuga pollo', c=['Pollo'], x='marinad empanad adobad hierbas', b='pechuga de pollo'),
 'Pechuga de pollo a la plancha': dict(de='Pechuga de pollo cruda', r=0.75),
 'Pepino': dict(q='pepino', c=['Pepino y zanahoria'], x='', b='pepino', u=300),
 'Pimiento rojo': dict(q='pimiento rojo', c=['Calabacín y pimiento'], x='asado', b='pimiento rojo'),
 'Pimiento verde': dict(q='pimiento verde', c=['Calabacín y pimiento'], x='', b='pimiento verde'),
 'Pistachos': dict(q='pistacho', c=['Frutos secos'], x='chocolate', b='pistachos'),
 'Plátano': dict(q='platano', c=['Plátano y uva'], x=SEM, b='platano'),
 'Queso cottage': dict(q='cottage', c=['Queso fresco'], x='', b='queso cottage'),
 'Queso curado': dict(q='queso curado', c=['Queso curado'], x='oveja cabra lonchas cheddar dados rallado semicurado tierno', b='queso curado'),
 'Queso feta': dict(q='feta', c=['Queso fresco', 'Queso especialidades', 'Queso tierno'], x='', b='queso feta', h='queso'),
 'Queso fresco': dict(q='queso fresco', c=['Queso fresco'], x='batido cottage crema burrata mozzarella untar', b='queso fresco'),
 'Queso fresco batido 0%': dict(q='queso fresco batido', c=['Queso fresco'], x='', b='queso fresco batido'),
 'Queso mozzarella light': dict(q='mozzarella', c=['Queso fresco'], x='bufala perlas', b='mozzarella', h='queso'),
 'Queso parmesano': dict(q='queso', c=['Queso rallado', 'Queso especialidades', 'Queso curado'], x='', b='parmesano', o='parmesano grana', h='queso'),
 'Quinoa cruda': dict(q='quinoa', c=['Arroz', 'Lentejas y otros'], x='cocida sabroz', b='quinoa'),
 'Quinoa cocida': dict(de='Quinoa cruda', r=2.7),
 'Remolacha cocida': dict(q='remolacha', c=['Otras verduras y hortalizas', 'Conservas verdura'], x='', b='remolacha cocida'),
 'Rúcula': dict(q='rucula', c=['Ensalada preparada', 'Lechuga'], x='', b='rucula'),
 'Salmón ahumado': dict(q='salmon ahumado', c=['Ahumados'], x='', b='salmon ahumado'),
 'Salmón crudo': dict(q='salmon', c=['Salmón', 'Pescado', 'Pescado congelado'], x='ahumado pate rosado medallones', b='salmon'),
 'Salsa de soja': dict(q='soja', c=['Salsas orientales'], x='', b='salsa de soja'),
 'Salsa sriracha': dict(q='chili', c=['Salsas orientales'], x='', b='sriracha'),
 'Semillas de chía': dict(q='chia', c=['Frutos secos', 'Cereales integrales y muesli'], x='muesli', b='semillas chia'),
 'Semillas de sésamo': dict(q='sesamo', c=['Frutos secos', 'Otras especias', 'Harina'], x='tahini', b='sesamo'),
 'Skyr o yogur griego 0%': dict(q='natural', o='proteina skyr', c=['Yogures desnatados'], x='fresa sabor lactosa azucarado', b='skyr natural'),
 'Tahini': dict(q='tahini', c=None, x='', b='tahini'),
 'Ternera magra cruda': dict(q='vacuno', c=['Vacuno'], x='picad hamburguesa higado', b='filetes ternera', o='filete'),
 'Tofu': dict(q='tofu', c=None, x='', b='tofu'),
 'Tomate': dict(q='tomate', c=['Tomate'], x='cherry seco triturado frito natural entero pelado tamizado concentrado troceado lata rallado', b='tomate'),
 'Tomate triturado': dict(q='tomate triturado', c=['Tomate'], x='', b='tomate triturado'),
 'Tomates secos': dict(q='tomate seco', c=None, x='', b='tomate seco'),
 'Tortilla de trigo integral': dict(q='tortillas trigo integral', c=['Pan de hamburguesa y wrap'], x='', b='tortillas integrales'),
 'Tortitas de arroz': dict(q='tortitas arroz', c=['Tortitas'], x='chocolate yogur', b='tortitas de arroz'),
 'Uvas': dict(q='uva', c=['Plátano y uva'], x=SEM + ' pasa', b='uva'),
 'Vinagre balsámico': dict(q='balsamico', c=['Vinagre y otros aderezos'], x='crema glaseado', b='vinagre balsamico'),
 'Vinagre de vino': dict(q='vinagre vino', c=['Vinagre y otros aderezos'], x='', b='vinagre de vino'),
 'Vino tinto': dict(q='vino tinto', c=['Vino tinto de mesa', 'Otros vinos tintos', 'Rioja', 'Castilla la Mancha'], x='', b='vino tinto'),
 'Yogur griego': dict(q='yogur griego natural', c=['Yogures griegos'], x='azucar', b='yogur griego natural'),
 'Yogur natural': dict(q='yogur natural', c=['Yogures naturales'], x='azucar edulcorado', b='yogur natural'),
 'Zanahoria': dict(q='zanahoria', c=['Pepino y zanahoria'], x='rallada baby', b='zanahoria'),
 'Zumo de limón': dict(q='limon', c=['Cítricos'], x='', b='limon', u=120, r=0.33),
 'Especias': None,
}
M.pop('Especias')
